[backend]
kind = "openai_like"
base_url = "http://localhost:11434/v1"
model = "llama3.1:8b"
api_key = ""
timeout_secs = 120
max_retries = 3
[backend.custom_params]

[policy]
approval = "on_request"
sandbox = "workspace_write"

[sandbox]
cpu_limit = 30
mem_limit_mb = 1024
net = "off"

[git]
conventional = true
max_staged_files = 10
use_notes = true

[provenance]
footer = true

[precommit]
rust = true
javascript = true
python = true

additional = []
fail_on = ["rust", "javascript", "python"]
allow_bypass_profiles = ["danger"]

[mcp]
profile = "std"

[mcp.approvals]

[quality]
max_test_failures = 0
max_lint_errors = 0
allow_lint_warnings = true
fail_on_missing_reports = false

[commit]
max_subject = 72
default_type = "refactor"
template_body = ".devit/commit_body.tmpl"

[commit.scopes_alias]
"crates/cli/src/mcp" = "mcp"
"crates/cli/src/context" = "context"
"crates/cli/src/plugins" = "plugins"
"crates/cli/src/bin" = "cli"
".github" = "ci"
"docs" = "docs"

[llm]
backend = "openai"
endpoint = "https://api.openai.com/v1"
model = "gpt-4"
timeout_s = 60
max_tokens = 2048