# -----------------------------
# crates/cli/Cargo.toml
# -----------------------------
[package]
name = "devit"
version = "0.1.0"
edition = "2021"


[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
serde = { workspace = true }
serde_yaml = { workspace = true }
tokio = { workspace = true }
toml = { workspace = true }
walkdir = { workspace = true }

# local crates
devit-common = { path = "../common" }
devit-agent = { path = "../agent" }
devit-tools = { path = "../tools" }
