# .github/ISSUE_TEMPLATE/bug_report.yml
name: Bug report
description: Signaler un bug
labels: [bug]
body:
  - type: textarea
    id: desc
    attributes: { label: Description, description: Que s’est-il passé ? }
    validations: { required: true }
  - type: textarea
    id: repro
    attributes: { label: Reproduction, description: Commandes exactes, logs, patch si possible }
    validations: { required: true }
  - type: input
    id: version
    attributes: { label: Version DevIt (`devit --version`) }
  - type: textarea
    id: env
    attributes: { label: Environnement, description: OS, backend LLM, config (`devit.toml`) }

