# .github/ISSUE_TEMPLATE/feature_request.yml
name: Feature request
description: Proposer une amélioration
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes: { label: Problème, description: Quel besoin ? }
    validations: { required: true }
  - type: textarea
    id: proposal
    attributes: { label: Proposition, description: API/CLI, flags, impacts sécurité }
  - type: textarea
    id: alt
    attributes: { label: Alternatives }

