## Sample configuration for DevIt (save as devit.toml at repo root)

[backend]
kind = "openai_like"
base_url = ""
model = ""
api_key = ""

[policy]
approval = "on_request"
sandbox  = "workspace-write"

[sandbox]
cpu_limit     = 1
mem_limit_mb = 64
net          = "off"

[git]
conventional     = true
max_staged_files = 10
use_notes        = true

[provenance]
footer = true

[precommit]
# Enable/disable families (defaults true if section absent)
rust = true
javascript = true
python = true
# Extra commands executed before apply (bash -lc context)
additional = [
  # "bash -lc 'make lint'"
]
# Families that fail the gate (others are best-effort)
fail_on = ["rust", "javascript", "python"]
# Profiles allowed to bypass with --no-precommit (requires --yes)
allow_bypass_profiles = ["danger"]

[mcp]
profile = "std"

#[mcp.approvals]
#"server.stats.reset" = "never"

[quality]
max_test_failures = 0
max_lint_errors = 0
allow_lint_warnings = true
fail_on_missing_reports = false

[commit]
max_subject = 72
default_type = "refactor"
template_body = ".devit/commit_body.tmpl"
scopes_alias = { "crates/cli/src/mcp" = "mcp", "crates/cli/src/context" = "context", "crates/cli/src/plugins" = "plugins", "crates/cli/src/bin" = "cli", ".github" = "ci", "docs" = "docs" }
