# -----------------------------
# crates/sandbox/Cargo.toml
# -----------------------------
[package]
name = "devit-sandbox"
version = "0.3.0"
edition = "2021"


[dependencies]
anyhow = { workspace = true }
devit-common = { path = "../common" }
