# -----------------------------
# crates/sandbox/Cargo.toml
# -----------------------------
[package]
name = "devit-sandbox"
version = "0.1.0"
edition = "2021"


[dependencies]
anyhow = { workspace = true }
