# -----------------------------
# crates/common/Cargo.toml
# -----------------------------
[package]
name = "devit-common"
version = "0.3.0"
edition = "2021"


[dependencies]
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
