name: Branch Name Policy

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  enforce:
    name: Enforce feat/* or fix/*
    runs-on: ubuntu-latest
    steps:
      - name: Check branch name
        run: |
          set -euo pipefail
          BRANCH="${{ github.head_ref }}"
          ACTOR="${{ github.actor }}"
          echo "PR head branch: $BRANCH (by $ACTOR)"
          # Allow common exceptions and bots
          if [[ "$ACTOR" == "dependabot[bot]" ]]; then
            echo "Dependabot PR detected, skipping branch name check."
            exit 0
          fi
          if [[ "$BRANCH" =~ ^(feat|fix|chore|docs|refactor|test|ci|release|dependabot)/.+$ ]]; then
            echo "Branch name accepted."
            exit 0
          fi
          echo "Branch name must start with one of: feat/, fix/, chore/, docs/, refactor/, test/, ci/, release/, dependabot/." >&2
          echo "Please rename the branch (e.g., 'feat/<topic>' or 'fix/<issue>')." >&2
          exit 1
