name: Sprint 5 - Create Issues

on:
  workflow_dispatch:
    inputs:
      labels:
        description: 'Comma-separated labels to apply to issues'
        required: false
        default: 'sprint5,enhancement'

jobs:
  open-issues:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Ensure milestone exists (Sprint 5)
        id: ms
        uses: actions/github-script@v7
        with:
          script: |
            const { data: milestones } = await github.rest.issues.listMilestones({ owner: context.repo.owner, repo: context.repo.repo, state: 'open' });
            let ms = milestones.find(m => m.title === 'Sprint 5');
            if (!ms) {
              const created = await github.rest.issues.createMilestone({ owner: context.repo.owner, repo: context.repo.repo, title: 'Sprint 5' });
              ms = created.data;
            }
            core.setOutput('number', String(ms.number));

      - name: Create issue - TUI scroll horizontal
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: 'TUI: horizontal scroll & wrap toggle'
          content-filepath: .github/issue-bodies/tui-scroll-horizontal.md
          labels: ${{ github.event.inputs.labels }}
          milestone: ${{ steps.ms.outputs.number }}

      - name: Create issue - TUI logs color
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: 'TUI: colorize JSONL logs by type'
          content-filepath: .github/issue-bodies/tui-logs-color.md
          labels: ${{ github.event.inputs.labels }}
          milestone: ${{ steps.ms.outputs.number }}

      - name: Create issue - TUI event stream
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: 'TUI: live event stream during run'
          content-filepath: .github/issue-bodies/tui-event-stream.md
          labels: ${{ github.event.inputs.labels }}
          milestone: ${{ steps.ms.outputs.number }}

      - name: Create issue - Sandbox bwrap mounts
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: 'Sandbox: bwrap mounts (workspace RW/RO, HOME RO, tmp private)'
          content-filepath: .github/issue-bodies/sandbox-bwrap-mounts.md
          labels: ${{ github.event.inputs.labels }}
          milestone: ${{ steps.ms.outputs.number }}

      - name: Create issue - Sandbox allow-list config
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: 'Sandbox: configurable allow-list for read-only'
          content-filepath: .github/issue-bodies/sandbox-allowlist-config.md
          labels: ${{ github.event.inputs.labels }}
          milestone: ${{ steps.ms.outputs.number }}

      - name: Create issue - Sandbox timeout in config
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: 'Sandbox: timeouts from devit.toml'
          content-filepath: .github/issue-bodies/sandbox-timeout-config.md
          labels: ${{ github.event.inputs.labels }}
          milestone: ${{ steps.ms.outputs.number }}

      - name: Create issue - Corrective run after FAIL
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: 'Run: corrective cycle after test FAIL'
          content-filepath: .github/issue-bodies/corrective-run-cycle.md
          labels: ${{ github.event.inputs.labels }}
          milestone: ${{ steps.ms.outputs.number }}

